"Welcome to Tic Tac Toe"
"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would X like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would O like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would X like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"what move would O like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would X like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would O like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would X like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"What move would O like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
"what move would X like to make (1-9)?"

"   |   |   "
"-----------"
"   |   |   "
"-----------"
"   |   |   "
