puts "Welcome to Tic Tac Toe"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would X like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would O like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would X like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "what move would O like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would X like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would O like to make (1-9)?"

puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "-----------"
puts "   |   |   "
puts "What move would X like to make (1-9)?"

